# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nrfutil (Linux x64)
        run: |
          curl -L https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o nrfutil
          sudo mv nrfutil /usr/bin/
          sudo chmod +x /usr/bin/nrfutil
          nrfutil --version

      - name: Install nrf5sdk-tools
        run: |
          nrfutil install nrf5sdk-tools

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Create venv
        run: uv venv .venv

      - name: Install CMake
        run: uv pip install cmake==4.1.2

      - name: Install west
        run: uv pip install west

      - name: Install Zephyr SDK
        run: |
          cd /opt
          sudo wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.17.4/zephyr-sdk-0.17.4_linux-x86_64.tar.xz
          sudo tar xf zephyr-sdk-0.17.4_linux-x86_64.tar.xz
          sudo mv zephyr-sdk-0.17.4 zephyr-sdk
          cd zephyr-sdk
          sudo ./setup.sh
          export ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk

      - name: Init west
        run: |
          west init

      - name: Update west and modules
        run: |
          west update

      - name: Install Zephyr Python requirements
        run: |
          uv pip install -r zephyr/scripts/requirements.txt

      - name: build firmware
        run: |
          export ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
          west build -b nrf52840dongle/nrf52840 zephyr/samples/bluetooth/hci_uart

      - name: create zip package
        run: |
          nrfutil nrf5sdk-tools pkg generate \
                  --hw-version 52 \
                  --sd-req=0x00 \
                  --application build/zephyr/zephyr.hex \
                  --application-version 1 \
                  nrf52840dongle_hci_uart.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nrf52840dongle_hci_uart.zip
          path: nrf52840dongle_hci_uart.zip