name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this workflow to be called by the release workflow
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Zephyr
        uses: actions/checkout@v4
        with:
          repository: zephyrproject-rtos/zephyr
          path: zephyr

      - name: Install nrfutil (Linux x64)
        run: |
          curl -L https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o nrfutil
          sudo mv nrfutil /usr/bin/
          sudo chmod +x /usr/bin/nrfutil
          nrfutil --version

      - name: Install nrf5sdk-tools
        run: |
          nrfutil install nrf5sdk-tools

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr
          toolchains: arm-zephyr-eabi

      - name: Build
        run: |
          west build -b nrf52840dongle/nrf52840 zephyr/samples/bluetooth/hci_uart

      - name: create zip package
        run: |
          nrfutil nrf5sdk-tools pkg generate \
                  --hw-version 52 \
                  --sd-req=0x00 \
                  --application build/zephyr/zephyr.hex \
                  --application-version 1 \
                  nrf52840dongle_bluetooth_hci_uart.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nrf52840dongle_bluetooth_hci_uart.zip
          path: nrf52840dongle_bluetooth_hci_uart.zip